name: Generate Data

on:
  workflow_dispatch:
    inputs:
      source:
        description: Which source to generate
        required: true
        default: all
        type: choice
        options:
          - all
          - netease
          - steam
          - github
          - bangumi
          # - bilibili
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: pnpm i

      - name: Generate netease data
        if: ${{ github.event.inputs.source == 'netease' || github.event.inputs.source == 'all' || github.event_name != 'workflow_dispatch' }}
        run: npm run generate:netease
        env:
          NETEASE_ID: ${{ secrets.NETEASE_ID }}
          NETEASE_FAVORITE_ID: ${{ secrets.NETEASE_FAVORITE_ID }}

      - name: Generate steam data
        if: ${{ github.event.inputs.source == 'steam' || github.event.inputs.source == 'all' || github.event_name != 'workflow_dispatch' }}
        run: npm run generate:steam
        env:
          STEAM_ID: ${{ secrets.STEAM_ID }}
          STEAM_KEY: ${{ secrets.STEAM_KEY }}
          STEAM_GAMES_EXCLUDE: ${{ secrets.STEAM_GAMES_EXCLUDE }}

      - name: Generate github data
        if: ${{ github.event.inputs.source == 'github' || github.event.inputs.source == 'all' || github.event_name != 'workflow_dispatch' }}
        run: npm run generate:github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}

      - name: Generate bangumi data
        if: ${{ github.event.inputs.source == 'bangumi' || github.event.inputs.source == 'all' || github.event_name != 'workflow_dispatch' }}
        run: npm run generate:bangumi
        env:
          BANGUMI_ID: ${{ secrets.BANGUMI_ID }}
          BANGUMI_USER_AGENT: ${{ secrets.BANGUMI_USER_AGENT }}

      # - name: Generate bilibili data
      #   if: ${{ github.event.inputs.source == 'bilibili' || github.event.inputs.source == 'all' || github.event_name != 'workflow_dispatch' }}
      #   run: npm run generate:bilibili

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: data/*
          message: "chore: update ${{ github.event.inputs.source == 'all' && 'all' || github.event.inputs.source }} data"
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
